name: Build and deploy Node.js app to Azure Web App - zalendovs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Clean install
        run: |
          find . -name 'node_modules' -exec rm -rf {} +
          npm ci --no-bin-links
          cd client && npm ci --no-bin-links

      - name: Build client
        run: |
          cd client && npm run build

      - name: Create deployment package
        run: |
          # Create minimal production package
          mkdir -p deployment

          # 1. Server files
          cp -r server deployment/
          cp package*.json deployment/

          # 2. Client files (only dist)
          mkdir -p deployment/client/dist
          cp -r client/dist/* deployment/client/dist/

          # 3. Azure required files
          echo "PORT=8080" > deployment/.env
          echo "NODE_ENV=production" >> deployment/.env

          # 4. Create startup script
          echo "#!/bin/sh" > deployment/startup.sh
          echo "cd /home/site/wwwroot" >> deployment/startup.sh
          echo "npm ci --production" >> deployment/startup.sh
          echo "node server/server.js" >> deployment/startup.sh
          chmod +x deployment/startup.sh

          zip -r release.zip deployment

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip -q release.zip -d deployment

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "zalendovs"
          slot-name: "Production"
          package: deployment
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_108B0C94D58C44839A2CA418B2D18AEE }}
          startup-command: "bash startup.sh" # Critical addition

      - name: Verify deployment
        run: |
          echo "Waiting for app to start..."
          sleep 60  # Increased wait time
          curl -sSf ${{ steps.deploy-to-webapp.outputs.webapp-url }}/health || (echo "Deployment failed"; exit 1)
