name: Build and deploy Node.js app to Azure Web App - zalendo-voting-system

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      # Server installation (from root)
      - name: Install server dependencies
        run: npm ci

      # Client installation and build
      - name: Install client dependencies
        run: |
          cd client
          npm ci
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Build client
        run: |
          cd client
          npm run build

      # Prepare deployment package
      - name: Create deployment package
        run: |
          # Create minimal deployment folder
          mkdir -p deployment
          
          # 1. Copy server files
          cp -r server deployment/
          cp package*.json deployment/
          
          # 2. Copy built client (just the dist folder)
          mkdir -p deployment/client
          cp -r client/dist deployment/client/
          
          # 3. Install only production deps
          cd deployment
          npm ci --production
          
          # Create zip (excluding hidden files)
          zip -r ../release.zip . -x ".*" -x "__MACOSX"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: |
          unzip -q release.zip -d deployment

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zalendo-voting-system'
          slot-name: 'Production'
          package: deployment
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1F7C564121BC41E292AB299957787336 }}
